# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

from .coinciding_geometry_checker import CoincidingGeometryChecker
from .colocated_vertices_checker import ColocatedVerticesChecker
from .duplicate_face_checker import DuplicateFaceChecker
from .duplicate_geometry_checker import DuplicateGeometryChecker
from .duplicate_geometry_fuzzy_checker import FuzzyDuplicateGeometryChecker
from .duplicate_materials_checker import DuplicateMaterialsChecker
from .empty_leaf_checker import EmptyLeafChecker
from .find_overlapping_meshes_checker import FindOverlappingMeshesChecker
from .flat_hierarchies_checker import FlatHierarchiesChecker
from .high_vertex_count_checker import HighVertexCountChecker
from .indexed_primvars_checker import IndexedPrimvarChecker
from .invisible_prims_checker import InvisiblePrimsChecker
from .isolated_vertices_checker import IsolatedVerticesChecker
from .nonmanifold_checker import NonManifoldChecker
from .normals_checker import NormalsChecker
from .occluded_meshes_checker import OccludedMeshesChecker
from .primitive_fit_checker import PrimitiveFitChecker
from .redundant_timesamples_checker import RedundantTimeSamplesChecker
from .rtx_mesh_count_checker import RtxMeshCountChecker
from .small_mesh_checker import SmallMeshChecker
from .sparse_mesh_checker import SparseMeshChecker
from .unused_uvs_checker import UnusedUVsChecker
from .windings_checker import WindingsChecker
from .zero_area_faces_checker import ZeroAreaFacesChecker
from .zero_extent_checker import ZeroExtentChecker
