[repo_py_package]
enabled = false
command = "py_package"
entry_point = "py_package:setup_repo_tool"
staging_dir = "$root/_build/pyproject"
install_dir = "$root/_build/packages"

[repo_usd_deps]
command = "usd"
entry_point = "usd:setup_repo_tool"
