import argparse
import json
import os
from typing import Callable, Dict

import omni.repo.man

# Libraries whose package version depends on the USD version being built against.
# Their version strings (per USD version) live in deps/usd-lib-deps.json. The
# generated file carries only the package versions; the linkPath for each library
# is declared once in deps/target-deps.packman.xml, which imports the generated
# file and merges the versions in by dependency name.
_USD_LIB_NAMES = (
    "omnimesh_ops_usd",
    "autouv-core",
    "shrinkwrap_openvdb",
)

# Template for the kit flavor: re-exports USD and Python from Kit SDK's all-deps
_KIT_USD_DEPS_TEMPLATE = """\
<project toolsVersion="5.6">
  <!-- USD from Kit SDK (kit flavor). Generated by the repo usd tool. Do not edit manually. -->
  <import path="../_build/${platform_target}/${config}/kit/dev/all-deps.packman.xml">
    <filter include="usd-${config}"/>
    <filter include="python" />
  </import>
  <dependency name="usd-${config}" linkPath="../_build/usd-deps/usd/${config}" />
  <dependency name="python" linkPath="../_build/usd-deps/python" />
</project>
"""

# Path to repo_usd packman templates, relative to its package root
_REPO_USD_TEMPLATE_SUBPATH = os.path.join("templates", "packman")


def _find_repo_usd_templates() -> str:
    """Return the path to the repo_usd packman templates directory.

    Searches in the standard repo deps location.
    """
    root = omni.repo.man.resolve_tokens("$root")

    # Check _repo/deps/repo_usd (standard dep location after pulling repo-deps)
    repo_deps_path = os.path.join(root, "_repo", "deps", "repo_usd", _REPO_USD_TEMPLATE_SUBPATH)
    if os.path.isdir(repo_deps_path):
        return repo_deps_path

    raise RuntimeError(
        "Could not find repo_usd template directory. "
        "Add 'repo_usd' to deps/repo-deps.packman.xml and run './repo.sh build' once to pull it."
    )


def _generate_usd_lib_deps(usd_ver: str, deps_dir: str) -> str:
    """Generate usd-lib-deps.generated.packman.xml for the given USD version.

    The USD-version-dependent libraries (omnimesh_ops_usd, autouv-core,
    shrinkwrap_openvdb) ship a different package per USD version. The version
    strings are sourced from ``<deps_dir>/usd-lib-deps.json``, keyed by USD
    version, and the generated file is written alongside it in ``deps_dir``.

    Unlike usd-deps, this file is not affected by ``--output-dir``:
    deps/target-deps.packman.xml imports it from ``deps/`` with a hardcoded
    relative path, so it must always be written there. Returns the path to the
    generated file.
    """
    lib_deps_json = os.path.join(deps_dir, "usd-lib-deps.json")
    with open(lib_deps_json) as f:
        lib_deps = json.load(f)

    if usd_ver not in lib_deps:
        available = sorted(lib_deps.keys())
        raise ValueError(
            f"No USD-dependent library versions defined for usd_ver='{usd_ver}' "
            f"in {lib_deps_json}. Available: {available}"
        )

    libs = lib_deps[usd_ver]

    lines = [
        '<project toolsVersion="5.6">',
        "  <!-- USD-version-dependent library versions. Generated by the repo usd tool",
        "       from deps/usd-lib-deps.json. Do not edit manually. The linkPath for each",
        "       library is declared in deps/target-deps.packman.xml. -->",
    ]
    for name in _USD_LIB_NAMES:
        packages = libs.get(name)
        if not packages:
            raise ValueError(
                f"Library '{name}' missing for usd_ver='{usd_ver}' in {lib_deps_json}."
            )
        lines.append(f'  <dependency name="{name}">')
        for pkg in packages:
            version = pkg["version"]
            platforms = pkg.get("platforms")
            if platforms:
                lines.append(
                    f'    <package name="{name}" version="{version}" platforms="{platforms}" />'
                )
            else:
                lines.append(f'    <package name="{name}" version="{version}" />')
        lines.append("  </dependency>")
    lines.append("</project>")

    output_path = os.path.join(deps_dir, "usd-lib-deps.generated.packman.xml")
    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return output_path


def setup_repo_tool(parser: argparse.ArgumentParser, config: Dict) -> Callable:
    parser.description = (
        "Tool to manage USD dependencies for Usd Optimize. "
        "Generates deps/usd-deps.generated.packman.xml for the selected USD flavor. "
        "Use 'kit' (default) to build against the Kit SDK USD, or specify a stock "
        "OpenUSD flavor. Supported non-kit flavors are listed in deps/usd_flavors.json."
    )
    omni.repo.man.add_config_arg(parser)

    parser.add_argument(
        "--generate-usd-deps",
        dest="generate_usd_deps",
        action="store_true",
        help="Generate deps/usd-deps.generated.packman.xml for the selected USD flavor.",
    )
    parser.add_argument(
        "--usd-flavor",
        dest="usd_flavor",
        default="usd",
        help=(
            "USD flavor to use. 'usd' (default) uses the standard usd libs. "
            "Other options: 'usd-minimal'. See deps/usd_flavors.json."
        ),
    )
    parser.add_argument(
        "--usd-ver",
        dest="usd_ver",
        default="26.08",
        help=(
            "USD version (e.g. '26.08'). Selects the stock OpenUSD deps template for "
            "non-kit flavors, and the USD-version-dependent library versions "
            "(omnimesh_ops_usd, autouv-core, shrinkwrap_openvdb) for all flavors, "
            "including kit."
        ),
    )
    parser.add_argument(
        "--python-ver",
        dest="python_ver",
        default="3.12",
        help="Python version (e.g. '3.12'). Use '0' for no-python (usd-minimal). Only used for non-kit flavors.",
    )
    parser.add_argument(
        "--output-dir",
        dest="output_dir",
        default=None,
        help="Output directory for usd-deps.generated.packman.xml (default: deps/).",
    )

    def run_repo_tool(options, config: Dict):
        if not options.generate_usd_deps:
            parser.print_help()
            return

        root = omni.repo.man.resolve_tokens("$root")
        output_dir = options.output_dir or os.path.join(root, "deps")
        usd_flavor = options.usd_flavor
        usd_ver = options.usd_ver
        python_ver = options.python_ver

        omni.repo.man.logger.info(
            f"Generating USD deps: flavor={usd_flavor}, ver={usd_ver}, python={python_ver}"
        )

        output_path = os.path.join(output_dir, "usd-deps.generated.packman.xml")

        if usd_flavor == "kit":
            with open(output_path, "w") as f:
                f.write(_KIT_USD_DEPS_TEMPLATE)
            omni.repo.man.logger.info(f"Generated kit USD deps: {output_path}")
        else:
            # A repo-local deps/usd-flavors/<flavor>/<usd_ver>+<python_ver>/ template wins over
            # repo_usd's, so versions repo_usd lacks a template for (26.08+) can still be built.
            version_key = f"{usd_ver}+{python_ver}"
            local_root = os.path.join(root, "deps", "usd-flavors")
            local_path = os.path.join(local_root, usd_flavor, version_key, "usd-deps.packman.xml")
            templates_root = local_root if os.path.isfile(local_path) else _find_repo_usd_templates()
            template_path = os.path.join(templates_root, usd_flavor, version_key, "usd-deps.packman.xml")
            if not os.path.isfile(template_path):
                flavor_dir = os.path.join(templates_root, usd_flavor)
                available = sorted(os.listdir(flavor_dir)) if os.path.isdir(flavor_dir) else []
                raise ValueError(
                    f"No template found for flavor='{usd_flavor}', ver='{usd_ver}', python='{python_ver}'. "
                    f"Expected: {template_path}\n"
                    f"Available for this flavor: {available}"
                )
            # Read as binary and normalize CRLF -> LF so the generated file has
            # consistent LF endings regardless of the template's authoring platform.
            # (Some upstream repo_usd templates ship with CRLF, which makes
            # git diff noisy on Linux/macOS due to text=auto normalization.)
            with open(template_path, "rb") as src:
                data = src.read().replace(b"\r\n", b"\n")
            with open(output_path, "wb") as dst:
                dst.write(data)
            omni.repo.man.logger.info(
                f"Generated {usd_flavor} USD {usd_ver}+py{python_ver} deps: {output_path}"
            )

        # Generate the USD-version-dependent library deps. Both its source JSON and
        # its generated file always live in <root>/deps: deps/target-deps.packman.xml
        # imports the generated file from deps/ with a hardcoded relative path, so
        # --output-dir (which only affects usd-deps.generated.packman.xml) must not
        # redirect it.
        deps_dir = os.path.join(root, "deps")
        lib_output_path = _generate_usd_lib_deps(usd_ver, deps_dir)
        omni.repo.man.logger.info(
            f"Generated USD-dependent library deps for usd_ver={usd_ver}: {lib_output_path}"
        )

    return run_repo_tool
